### ISSUE TITLE
auth token好像拿不到私人仓库

### ISSUE THREAD

**Issue by huxiaofan1223** [CarGuo/GSYGithubAPP#100]
auth token好像拿不到私人仓库

**Comment by CarGuo** [comment]
这个和配置时授权的参数有关系吧我记得

**Comment by huxiaofan1223** [comment]
这个我也不太清楚，如果走githubapp的话好像还要私人授权安装才能拿到私人仓库，走oauth的话好像连调权限的机会都没有
