### ISSUE TITLE
APP 反馈

### ISSUE THREAD

**Issue by hccopy** [CarGuo/GSYGithubAPP#14]
![](http://osvlwlt4g.bkt.clouddn.com/2017-12-27/1514366130869.jpg)  ![](http://osvlwlt4g.bkt.clouddn.com/2017-12-27/1514366135775.jpg)  ![](http://osvlwlt4g.bkt.clouddn.com/2017-12-27/1514366147853.jpg)

**Comment by CarGuo** [comment]
😏居然有人测试反馈了？
