### ISSUE TITLE
我的github登不上去

### ISSUE THREAD

**Issue by kukudedaxia** [CarGuo/GSYGithubAPP#17]
![image](https://user-images.githubusercontent.com/30620856/34637041-7e8e1b72-f2e8-11e7-9523-3b4ddd4863ce.png)
![image](https://user-images.githubusercontent.com/30620856/34637042-83458bb4-f2e8-11e7-8a65-18eb41c3fc9f.png)

**Comment by CarGuo** [comment]
你是开启了二次认证的账号吗？？可以看看返回的message错误是什么，我这边没发现登陆不上呢

**Comment by CarGuo** [comment]
如果是自己编译的，请确保github的开发id正确
