### ISSUE TITLE
报错 'React/RCTBundleURLProvider.h' file not found  

### ISSUE THREAD

**Issue by zhanghao-web** [CarGuo/GSYGithubAPP#18]
报错 无法运行是怎么回事？

**Comment by CarGuo** [comment]
看看install是否完全安装成功

**Comment by zhanghao-web** [comment]
Error: EACCES: permission denied, mkdir '/Users/mac/.npminstall_tarball/b' 这个失败了  install 时  需要在前面加sudo吗？

**Comment by CarGuo** [comment]
这个得看个人环境问题，我是不需要的

**Comment by zhanghao-web** [comment]
可以先跳过ignoreConfig.js的创建 ，直接在xcode运行吗？

**Comment by CarGuo** [comment]
其实最简单就是创建一个，然后都返回空字符串
