### ISSUE TITLE
您好，请问Login页面如何登陆呢？

### ISSUE THREAD

**Issue by miluokesiji** [CarGuo/GSYGithubAPP#22]
卡在LoginPage登陆失败~~~

**Comment by CarGuo** [comment]
你是自己编译的还是下载的？？？

**Comment by CarGuo** [comment]
如果是你自己编译的，请确保ignoreConfig的github id与sercet正确，具体可以在首页链接去申请

**Comment by miluokesiji** [comment]
哦，我没有配置那个。首页链接Oauth没太理解。本地用安卓模拟器，如何设置那个url呢。

**Comment by CarGuo** [comment]
其实就是你需要在这里 https://github.com/settings/applications/new 创建一个app，和创建微信分享哪种一样，然后把得到的github client_id 和github client_secret填写在ignoreConfig.js文件里

```
 export const CLIENT_ID = "你的client_id ";

 export const CLIENT_SECRET = "你的client_secret";

```

**Comment by miluokesiji** [comment]
哦，行了。就是创建一个访问接口，是吗？新人，刚找个项目来拜读，感谢答复。本地已成功。那个URL用的百度的。。。具体还不太了解作用。谢谢！
不知道前辈有没实战的推荐，个人没完整做过APP项目，谢谢1

**Comment by CarGuo** [comment]
其实就是做了一个认证，通过这个id和sercet，github知道你的授权访问是合法的。

这么说吧，就是这个id和sercet代表着你编译的app的唯一性和安全性。
