### ISSUE TITLE
Android版，没有任何操作的情况下，通过Profile GPU rendering看到app在不停地渲染

### ISSUE THREAD

**Issue by ansonhorse** [CarGuo/GSYGithubAPP#23]
![gsygithubapp-issue-simulator](https://user-images.githubusercontent.com/7548142/35077977-d73025e4-fc3a-11e7-8d41-01efb577b21e.gif)
你好，对RN和Android开发都比较陌生，现在有RT所述的疑问。
app是release的，如图所示，在没有任何操作的情况下，不清楚为什么还会有渲染在进行。真机和模拟器，都有这个情况出现。
升级到1.4版本，也就是作者你打包发布的，没发现有这个问题。

**Comment by CarGuo** [comment]
你可以看升级说明，并没修改过这方面的。

**Comment by CarGuo** [comment]
这个页面并没有做试试刷新，这么奇怪···
