### ISSUE TITLE
":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by zhang6321615** [CarGuo/GSYGithubAPP#26]
描述:
react-native run-ios

错误:

The following build commands failed:
	CompileC /Users/******/work/GSYGithubAPP/ios/build/Build/Intermediates/imageCropPicker.build/Debug-iphonesimulator/imageCropPicker.build/Objects-normal/x86_64/ImageCropPicker.o ImageCropPicker.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/GSYGithubAPP.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/GSYGithubAPP.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

附加信息: 
版本: react-native 0.50.1
Android 可以  iOS不可以
信息信息: MacOS 10.13.3

**Comment by CarGuo** [comment]
你真机运行的话，要用你自己的bundle id

**Comment by zhang6321615** [comment]
我用的是模拟器运行的。
XCode 的模拟器  Iphone6s

**Comment by CarGuo** [comment]
直接xcode运行？如果是命令行运行的话还需要配置命令行环境的。
