### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by CS-Tao** [CarGuo/GSYGithubAPP#27]
你好~请问一下，开启二次验证后不能登录吗？可以怎么解决呢？

**Comment by CarGuo** [comment]
目前没有增加二次验证的处理，之前是想要添加二次验证功能，但是在开通时居然没有找到中国的号码···

**Comment by CS-Tao** [comment]
我是用的App开通的二次验证，好像是`Duo Mobile`？您之后有空的话可以试一下？期待这个功能
