### ISSUE TITLE
问一个状态管理的问题

### ISSUE THREAD

**Issue by zhengcx** [CarGuo/GSYGithubAPP#28]
我看这个项目里有一部分状态是用redux来管理，有一部分状态又是直接在组件里setState,想问一下这个有什么讲究吗，什么时候用redux来管理状态，什么时候可以直接setState，谢谢~

**Comment by CarGuo** [comment]
redux属于内存常驻，一般我习惯用在登录的用户信息，和一些全局到你单一常驻内存的东西，如果有需要还可以对这些信息进行持久化。
比如一些信息是不常驻的，而且可以一次打开多个的，比如详情页，我个人比较习惯直接用本地state
