### ISSUE TITLE
iOS编译错误

### ISSUE THREAD

**Issue by SplashZ** [CarGuo/GSYGithubAPP#32]
如题和图 [http://opq90ineu.bkt.clouddn.com/111.png](如图)

+ DEST=/Users/macintosh/Library/Developer/Xcode/DerivedData/GSYGithubAPP-chscgatpmvnxkzcyxioglgauycnc/Build/Products/Release-iphoneos/GSYGithubAPP.app
+ [[ Release = \D\e\b\u\g ]]
+ BUNDLE_FILE=/Users/macintosh/Library/Developer/Xcode/DerivedData/GSYGithubAPP-chscgatpmvnxkzcyxioglgauycnc/Build/Products/Release-iphoneos/GSYGithubAPP.app/main.jsbundle
+ node '/Users/macintosh/react native/RNtest/GSYGithubAPP-master/node_modules/react-native/local-cli/cli.js' bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/macintosh/Library/Developer/Xcode/DerivedData/GSYGithubAPP-chscgatpmvnxkzcyxioglgauycnc/Build/Products/Release-iphoneos/GSYGithubAPP.app/main.jsbundle --assets-dest /Users/macintosh/Library/Developer/Xcode/DerivedData/GSYGithubAPP-chscgatpmvnxkzcyxioglgauycnc/Build/Products/Release-iphoneos/GSYGithubAPP.app
Scanning folders for symlinks in /Users/macintosh/react native/RNtest/GSYGithubAPP-master/node_modules (10ms)
Scanning folders for symlinks in /Users/macintosh/react native/RNtest/GSYGithubAPP-master/node_modules (81ms)

Unexpected token ， in JSON at position 1486

+ [[ false != true ]]
+ [[ ! -f /Users/macintosh/Library/Developer/Xcode/DerivedData/GSYGithubAPP-chscgatpmvnxkzcyxioglgauycnc/Build/Products/Release-iphoneos/GSYGithubAPP.app/main.jsbundle ]]
+ echo 'error: File /Users/macintosh/Library/Developer/Xcode/DerivedData/GSYGithubAPP-chscgatpmvnxkzcyxioglgauycnc/Build/Products/Release-iphoneos/GSYGithubAPP.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/macintosh/Library/Developer/Xcode/DerivedData/GSYGithubAPP-chscgatpmvnxkzcyxioglgauycnc/Build/Products/Release-iphoneos/GSYGithubAPP.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2

**Comment by CarGuo** [comment]
有没有参考首页教程，参见ignoreConfig文件
