### ISSUE TITLE
npm install 出现以下问题了，是因为没有安装.netframework 2.0？

### ISSUE THREAD

**Issue by hrx3627** [CarGuo/GSYGithubAPP#33]
![image](https://user-images.githubusercontent.com/4224913/38482617-a95e2316-3c02-11e8-9acb-0c86b0967fa8.png)

**Comment by CarGuo** [comment]
这个理论上不影响使用

**Comment by CarGuo** [comment]
你找一下default是哪的，为什么没有，gradle文件

**Comment by hrx3627** [comment]
应该不是default的问题哦，我看了下我的realm库没有下载下来
