### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by vitaminbat** [CarGuo/GSYGithubAPP#34]
如图
![http://p6v1w91z5.bkt.clouddn.com/1111.png](http://p6v1w91z5.bkt.clouddn.com/1111.png)
按readme的方法，也在~/.rncache里加了第三方编译库

**Comment by CarGuo** [comment]
你这个看起来像是npm按照的nodemodule有问题

**Comment by vitaminbat** [comment]
那重装下
