### ISSUE TITLE
登陆不进去

### ISSUE THREAD

**Issue by songshitong** [CarGuo/GSYGithubAPP#39]
作者，您好，是这样的：
     我在使用过程中，输入用户名和和密码会自动消失，剩下的内容是不完整的，不知道这是不是你做的特效，我是靠粘贴账号和密码才登陆成功的。

**Comment by songshitong** [comment]
说一下机型，红米note4，android6.0

**Comment by CarGuo** [comment]
有可能是背景lottie动画导致的

**Comment by CarGuo** [comment]
已经更新解决

**Comment by songshitong** [comment]
实测可以了，给作者点个赞👍
