### ISSUE TITLE
要翻墙？

### ISSUE THREAD

**Issue by jp1017** [CarGuo/GSYGithubAPP#40]
![tim 20180703102323](https://user-images.githubusercontent.com/7868514/42195366-2416043a-7eab-11e8-85aa-9ea59f00920e.png)

**Comment by jp1017** [comment]
明白了，复制一个过去试试

**Comment by jp1017** [comment]
各种依赖找不到，，，arch

**Comment by jp1017** [comment]
还有好多找不到的，你都怎么搞的，一个一个复制？

**Comment by CarGuo** [comment]
你重新更新代码了没？？

**Comment by jp1017** [comment]
没啊，啥也没动

**Comment by CarGuo** [comment]
重新拉下代码，更加了  google() 的maven

**Comment by jp1017** [comment]
>FAILURE: Build failed with an exception.

* Where:
Build file 'E:\GSYGithubAPP-master\android\build.gradle' line: 6

* What went wrong:
A problem occurred evaluating root project 'GSYGithubAPP'.
> Could not find method google() for arguments [] on repository container.

**Comment by jp1017** [comment]
我之前就加了，报这个，奇怪， 改成3.1.3也不行

**Comment by CarGuo** [comment]
https://github.com/airbnb/lottie-android/issues/822#issuecomment-4017
和上面说的一样，lottite这几天更新的android版本，而它的react插件用的是+，所以导致更新后不兼容

`compile 'com.airbnb.android:lottie:2.5.+'`

我刚刚处理了，可以正常编译了，你试试。
 
先`cd android ` 执行个gradlew clean

然后 再回根目录执行react-native run-android
