### ISSUE TITLE
load js成功后路由报错

### ISSUE THREAD

**Issue by lyxia** [CarGuo/GSYGithubAPP#42]
运行报错
![img_8052](https://user-images.githubusercontent.com/7269593/44024163-21fa8132-9f1f-11e8-98d5-7dd621201469.PNG)

**Comment by lyxia** [comment]
你好，我在代码中看到路由的配置如下：
![648ded39-8450-43ec-858a-47c9e18c257c](https://user-images.githubusercontent.com/7269593/44025024-80ff25d2-9f21-11e8-8687-d5e92d920d9b.png)
但是reset的使用如下：
![e0396f40-18b2-46e2-ab75-978be71f7c39](https://user-images.githubusercontent.com/7269593/44025039-8d88a986-9f21-11e8-9111-a0d69e8af2e1.png)
这其中牵扯的源码如下：
![1d783a00-c6e2-4e0b-8d4b-99b76daf592a](https://user-images.githubusercontent.com/7269593/44025060-9bc50e7c-9f21-11e8-8d29-619c2aff3df2.png)
![1ea5dab5-b678-4979-9a58-5cd57be8d462](https://user-images.githubusercontent.com/7269593/44025067-a1625218-9f21-11e8-8a9b-319b7a8c74a9.png)

我的理解是LoginPage是二级路由，通过reset来直接写入二级路由是不合理的，应该写入一级路由root，然后使用navigate的action参数来跳转二级路由LoginPage，但是在flux-router中我没发现它的reset支持这个功能，所以还麻烦作者告知要如何修改。
因为之前的项目是直接使用了react-navigation，没有使用更高级的flux-router封装，不知道是不是我拉代码或运行的方式有问题？

**Comment by CarGuo** [comment]
你运行demo报错？可以看看是不是库的版本在npm 的时候更新了

**Comment by CarGuo** [comment]
我这边测试正常。
如果说的是GSY项目中的路由，是这样的。
router-flux中
显示有一个LightBox，这是用于弹出模态框的
然后第一个Scene是root，里面的二级Scene才是页面承载
然后和root同级别的其他Scene，其实就是模态

**Comment by lyxia** [comment]
![b9272ab0-8691-4826-a8de-73b5916dd792](https://user-images.githubusercontent.com/7269593/44075381-30a8643c-9fcf-11e8-96e8-d5d841883ebd.png)
![d6c95579-7886-4313-8c0a-b21ea9fc04b2](https://user-images.githubusercontent.com/7269593/44075383-310eff44-9fcf-11e8-87ad-53f9fb8c291c.png)
这是我本地的路由版本号，你的是多少

**Comment by CarGuo** [comment]
"react-native-router-flux": "^4.0.0-beta.31"

我直接新clone项目，然后npm install，然后运行，没问题。

个人建议你删除整个项目下的node_model文件夹，在重新npm install，注意期间是否有错误。

![5b727915e4b0cdb6810cffdf](https://user-images.githubusercontent.com/10770362/44075590-e19ab06a-9fcf-11e8-869d-33241118e160.jpg)

**Comment by lyxia** [comment]
哎 删了重拉也不行 我用的是yarn install， yarn.lock也删了，中途没报任何错，没辙了

**Comment by CarGuo** [comment]
奇怪，我换了台电脑测试也没事：！

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAPP/issues/45

**Comment by CarGuo** [comment]
重新拉下代码，在yarn更新下，应该可以了，貌似是因为基础的navigation在安装的时候版本升级了

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAPP/issues/45#issuecomment-413799130
