### ISSUE TITLE
这个问题要怎么解决呢

### ISSUE THREAD

**Issue by shdulu** [CarGuo/GSYGithubAPP#45]
![image](https://user-images.githubusercontent.com/35714137/44252882-54d25300-a230-11e8-826f-b81d446f3c6f.png)

**Comment by CarGuo** [comment]
奇怪。为什么你们会出现这个问题…

**Comment by CarGuo** [comment]
你是用yarn还是npm

**Comment by CarGuo** [comment]
初步怀疑是react-native-flux-router 版本问题

**Comment by CarGuo** [comment]
https://github.com/aksonov/react-native-router-flux/issues/2724

**Comment by CarGuo** [comment]
![5b766fade4b0cdb681119971](https://user-images.githubusercontent.com/10770362/44254015-12127a00-a234-11e8-9f66-19b3c794c245.png)
![5b767be8e4b06b84d540da6e](https://user-images.githubusercontent.com/10770362/44254018-15a60100-a234-11e8-886c-6aca11f26db0.png)

**Comment by CarGuo** [comment]
目前初步确定，应该是更新的库不一致

**Comment by shdulu** [comment]
npm install 安装不成功，用的yarn

**Comment by CarGuo** [comment]
重新拉下代码，在yarn更新下，应该可以了

**Comment by shdulu** [comment]
![image](https://user-images.githubusercontent.com/35714137/44255565-12614400-a239-11e8-9d8a-5cf73041e447.png)

**Comment by shdulu** [comment]
你那里在github上拉下来 安装依赖可以运行的吗

**Comment by shdulu** [comment]
可以了谢谢大牛

**Comment by CarGuo** [comment]
我刚刚又更新了下router.js，主要还是升级后的router-flux和navigation不兼容旧的写法，刚刚更新适配后就好了
