### ISSUE TITLE
登陆问题

### ISSUE THREAD

**Issue by shdulu** [CarGuo/GSYGithubAPP#46]
无法登陆啊

**Comment by CarGuo** [comment]
自己编译的请看readme，使用正确的appId,用自己的github账号登陆。

**Comment by shdulu** [comment]
按照readme里写的添加了ignoreConfig.js文件 用自己的gihub账号无法登录

**Comment by CarGuo** [comment]
你可以看下网络返回提示什么，猜测是申请的Github client_id 和 client_secret 没对

**Comment by shdulu** [comment]
谢了
