### ISSUE TITLE
编译问题。。。

### ISSUE THREAD

**Issue by junchenChow** [CarGuo/GSYGithubAPP#53]
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/2.18.0/realm-v2.18.0-node-v64-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for realm@2.18.0 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB4132: 无法识别工具版本“2.0”。可用的工具版本为 "4.0"。
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\node\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\node\\node.exe" "D:\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\react-native-pro\\GSYGithubAPP\\node_modules\\realm\\compiled\\node-v64_win32_x64\\realm.n
ode" "--module_name=realm" "--module_path=D:\\react-native-pro\\GSYGithubAPP\\node_modules\\realm\\compiled\\node-v64_win32_x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd D:\react-native-pro\GSYGithubAPP\node_modules\realm
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\node\node.exe D:\node\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\react-native-pro\GSYGithubAPP\node_modules\realm\compiled\node-v64_win32_x64
\realm.node --module_name=realm --module_path=D:\react-native-pro\GSYGithubAPP\node_modules\realm\compiled\node-v64_win32_x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\react-native-pro\GSYGithubAPP\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "D:\\node\\node.exe" "D:\\react-native-pro\\GSYGithubAPP\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\react-native-pro\GSYGithubAPP\node_modules\realm
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'D:\node\node.exe D:\node\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\react-native-pro\GSYGithubAPP\node_modules\realm\compiled\node-v64_win32_x64\realm.node --module_name=realm
 --module_path=D:\react-native-pro\GSYGithubAPP\node_modules\realm\compiled\node-v64_win32_x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN react-native@0.57.1 requires a peer of react@16.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@2.18.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@2.18.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhoujunchen\AppData\Roaming\npm-cache\_logs\2018-11-01T09_10_14_820Z-debug.log

Process finished with exit code 1

刚开始玩RN 对于一些集成编译的问题还是没什么经验~

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAPP/issues/52  貌似这里有你要的答案
