### ISSUE TITLE
utf-8 非法字符 无法编译

### ISSUE THREAD

**Issue by Asen2019** [CarGuo/GSYGithubAPP#57]
<img width="828" alt="image" src="https://user-images.githubusercontent.com/47095780/51953386-24494300-2477-11e9-8012-5ea1cbc52ea8.png">

<img width="939" alt="image" src="https://user-images.githubusercontent.com/47095780/51953413-40e57b00-2477-11e9-844e-131bc0418713.png">

两个 module的 package utf-8编码非法字符 无法编译

**Comment by CarGuo** [comment]
已更新，请拉去代码后重新安装
