### ISSUE TITLE
运行react-native run-android后卡在启动页面

### ISSUE THREAD

**Issue by PENG199** [CarGuo/GSYGithubAPP#61]
运行react-native run-android后卡在启动页面,没有报错信息。
但是真机没有问题，只是在模拟器上卡住了
![image](https://user-images.githubusercontent.com/12715867/52925251-5ad5f780-336b-11e9-872c-8291efdb4ab8.png)
![image](https://user-images.githubusercontent.com/12715867/52925257-5f9aab80-336b-11e9-90f0-5bb797a7dbe8.png)

**Comment by CarGuo** [comment]
这个可能和so相关吧。现在很少用模拟器

**Comment by PENG199** [comment]
嗯嗯，应该是的。现在突然又可以了。
