### ISSUE TITLE
realm老是404，换了好几个版本都是404

### ISSUE THREAD

**Issue by sunbest110** [CarGuo/GSYGithubAPP#63]

**Comment by CarGuo** [comment]
你npm能装下realm吗？单独npm试试

**Comment by sunbest110** [comment]
报错以后，我就开始单独装了，不行

**Comment by sunbest110** [comment]
> 你npm能装下realm吗？单独npm试试

你的可以吗？

**Comment by CarGuo** [comment]
可以

<img width="573" alt="image" src="https://user-images.githubusercontent.com/10770362/54803772-d8af5a80-4cab-11e9-90f8-13577f8030c8.png">

**Comment by sunbest110** [comment]
> 可以
> 
> <img alt="image" width="573" src="https://user-images.githubusercontent.com/10770362/54803772-d8af5a80-4cab-11e9-90f8-13577f8030c8.png"

**Comment by sunbest110** [comment]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/12553543/54804665-4c069b80-4caf-11e9-994b-238c852fcc1c.png">
我用的这个
