### ISSUE TITLE
难受

### ISSUE THREAD

**Issue by sunbest110** [CarGuo/GSYGithubAPP#64]
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/12553543/54810048-01414f80-4cc0-11e9-87f9-612012b0853e.png">
不小心关掉了

**Comment by CarGuo** [comment]
推测，node的版本问题

**Comment by sunbest110** [comment]
你的版本是多少？

**Comment by CarGuo** [comment]
node -v
v10.4.0

**Comment by lionnner** [comment]
node: v8.15.1
vscode: 1.32.3
xcode: 10.2
Error: 执行命令 react-native run-ios --simulator --no-packager 时出错

**Comment by CarGuo** [comment]
@lionnner 出错什么

**Comment by lionnner** [comment]
@CarGuo 
我先说下我的操作步骤：
1.下载下来后，进入到下载文件的根目录 执行 npm install
2.用的 visual studio code 打开了下载的目录
3.点击 vscode的设置自动生成了launch.json
4.我就直接进行 debug running 然后就报了错 "Error: 执行命令 react-native run-ios --simulator --no-packager 时出错"
5.我本身是iOS开发人员，打开了对应生成的工程

环境如下：
react-native-cli: 2.0.1
react-native: 0.57.8
node version: v10.15.2

<img width="1579" alt="88E2B9C5-56CD-42DE-AD4F-ED5DAA605704" src="https://user-images.githubusercontent.com/19425203/55313881-7ddfe500-549b-11e9-8c12-77360e0b4389.png">
<img width="1111" alt="A9ED51FF-D7E7-47E2-801F-E8F2F2F13E0E" src="https://user-images.githubusercontent.com/19425203/55315684-6c98d780-549f-11e9-8778-d3f7927b46d8.png">

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAPP/issues/66
