### ISSUE TITLE
编译报错 Execution failed for task ':app:processDebugResources'.

### ISSUE THREAD

**Issue by LaymanInCoding** [CarGuo/GSYGithubAPP#65]
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.

**Comment by CarGuo** [comment]
这样看不出来问题

**Comment by LaymanInCoding** [comment]
好吧，我再试试，先把issue关掉了，谢谢大佬

**Comment by LaymanInCoding** [comment]
C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\f426d496ac0c44ad1261d82099102b0d\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCorne
rRadius not found.

E:\GSYGithubAPP\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.

C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\f426d496ac0c44ad1261d82099102b0d\res\values\values.xml:1304:5-69: AAPT: error: resource android:attr/fontVariationSettin
gs not found.

C:\Users\Administrator\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\f426d496ac0c44ad1261d82099102b0d\res\values\values.xml:1304:5-69: AAPT: error: resource android:attr/ttcIndex not found.

error: failed linking references.

**Comment by LaymanInCoding** [comment]
找到原因了，修改lottie-react-native module下的build.gradle 
将api 'com.android.support:appcompat-v7:28.0.0'修改
api 'com.android.support:appcompat-v7:27.0.1'
