### ISSUE TITLE
README，img

### ISSUE THREAD

**Issue by yongqi-zhang** [CarGuo/GSYGithubAPP#69]
您好，最近正在阅读您的源码，看到readme里面图片的展示问题，没有看懂，不知道您方不方便详细说明下这里的逻辑呢
PS：直接使用github地址作为img的src，是无法加载图片的

**Comment by CarGuo** [comment]
是的，你需要给 url + raw=true 或者 替换为 raw 的连接，具体你复制 github 的图片出现显示就知道了
