### ISSUE TITLE
关于list 列表 no more 逻辑

### ISSUE THREAD

**Issue by yongqi-zhang** [CarGuo/GSYGithubAPP#71]
您好，读您代码的时候。这里的逻辑没有看懂，api的返回值没有 总数 ，我们是根据什么条件来判断已经加载不到新数据了呢？还有这里的逻辑，写在 action里面合适呢？还是页面里面合适呢？

**Comment by CarGuo** [comment]
默认是我设置了请求每页20个，如果返回不满20就当作后面没有了。

其实github api 的返回 header也有返回页数，比如我记得用户的 starred 就是通过这个header提取出来的。

至于这个逻辑写在那里，就看你loadmore的状态写在哪里了

**Comment by yongqi-zhang** [comment]
返回不满20这个逻辑我看到了，starred的逻辑也找到了，看起来不是每个api都有header 的link，比如follower 如果正好是20个数据就会误判。

**Comment by CarGuo** [comment]
没事的，刚好20个，你再请求一次就返回[]，就no more
