### ISSUE TITLE
android 9，API版本28，但是启动报错

### ISSUE THREAD

**Issue by kavience** [CarGuo/GSYGithubAPP#72]
Unable to load script..Make sure you're either running a Metro server(run 'react-native start) or that your bundle 'index.android.bundle' is packaged correctly for release

**Comment by kavience** [comment]
但是build已经成功了，而且Metro也正常启动，但是在模拟器上打开还是这个错误

**Comment by CarGuo** [comment]
没连接上你的 metro

**Comment by kavience** [comment]
老司机有没有打包和发布的流程呢？期待。。。

**Comment by CarGuo** [comment]
什么打包发布流程？
打包android直接 ./gradlew assembleRelease 就好了
打包ios 直接Xcode archive 就好了
