### ISSUE TITLE
apk运行问题

### ISSUE THREAD

**Issue by OMGyan** [CarGuo/GSYGithubAPP#73]
apk下载安装后，启动不了，崩溃

**Comment by CarGuo** [comment]
二维码的那个apk？

**Comment by OMGyan** [comment]
> 二维码的那个apk？

嗯

**Comment by CarGuo** [comment]
奇怪，我这边试了几台手机都正常

**Comment by OMGyan** [comment]
![Screenshot_20190625-102254](https://user-images.githubusercontent.com/25549811/60064671-b65a2c80-9733-11e9-97b6-81bec772907b.jpg)

**Comment by OMGyan** [comment]
flutter版本正常

**Comment by OMGyan** [comment]
手机：Honor 8 Lite  Android版本：8.0.0

**Comment by CarGuo** [comment]
试试这个

[app-release.zip](https://github.com/CarGuo/GSYGithubAPP/files/3323335/app-release.zip)

**Comment by CarGuo** [comment]
还有问题吗？

**Comment by OMGyan** [comment]
压缩包下载太慢了，还没装呢
