### ISSUE TITLE
为什么自己写fetch请求会出现跨域的问题？

### ISSUE THREAD

**Issue by Wutian0114** [CarGuo/GSYGithubAPP#75]
我想自定义请求url，就会出现"Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."或者“unsupported BodyInit type”。还有就是在“Debug JS Remotely”的时候，可以再Chrome的network里看到提交的请求，一般情况不是看不到吗？

**Comment by Wutian0114** [comment]
还有就是在“Debug JS Remotely”的时候，可以再Chrome的network里看到提交的请求，一般情况不是看不到吗？

**Comment by CarGuo** [comment]
不是很理解你的意思？你的项目还是我现在的？？

**Comment by Wutian0114** [comment]
> 不是很理解你的意思？你的项目还是我现在的？？

就是你的项目，我想修改登录的url，会出现跨域这个问题。于是我就自己写了请求，登录页面加了这个`fetch('https://raw.githubusercontent.com/facebook/react-native/0.51-stable/docs/MoviesExample.json')
    .then(response => response.json())
    .then(responseData => {
    });`，然后就会出现“unsupported BodyInit type”，
![image](https://user-images.githubusercontent.com/14009344/60331852-2b459480-99c8-11e9-8469-288e96a0db94.png)

**Comment by CarGuo** [comment]
跨域有时候是后台做了限制的。

至于 unsupported BodyInit type 是返回数据处理有问题

**Comment by Wutian0114** [comment]
感谢解答！
