### ISSUE TITLE
进 详情页 ios 报错 

### ISSUE THREAD

**Issue by cham1985** [CarGuo/GSYGithubAPP#76]
![1561868914334](https://user-images.githubusercontent.com/7087874/60392310-b93d8e80-9b32-11e9-8747-9b43abd1d4cd.jpg)

**Comment by CarGuo** [comment]
已修复，拉完代码之后，重新 npm ，之后 xcode clean 之后 build 就好了

**Comment by cham1985** [comment]
好的，谢谢大佬，但是  Realm 又 安装报错了
![image](https://user-images.githubusercontent.com/7087874/60419232-5d990100-9c17-11e9-8e6f-9e3da04bc355.png)

**Comment by CarGuo** [comment]
这个得看是不是没有安装成功

**Comment by CarGuo** [comment]
你试试直接用xocde 运行

**Comment by cham1985** [comment]
确实 没 安装 成功，xcode build 也报错，ld: library not found for -lRealmReact
，是不是我 node 版本 太高了 ？v12.5.0

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAPP/issues/50

**Comment by cham1985** [comment]
多谢大佬，现在 react-native link  时，react-native-spinkit 这个库报错了 
![image](https://user-images.githubusercontent.com/7087874/60433604-d1e39c80-9c37-11e9-9c64-d24e91d84e1b.png)
