### ISSUE TITLE
Android 8.0  启动闪退

### ISSUE THREAD

**Issue by zhuhaihang** [CarGuo/GSYGithubAPP#79]
8.0 启动闪退报错 Only fullscreen opaque activities can request orientation。也就是说只有全屏不透明的activity才可以设置方向。手动取消App启动白屏或者黑屏的时候，将Splash界面设为了透明，然后这个时候又设置了方向为垂直，从而导致了这个问题。
解决：
1.找到你设置透明的Activity，然后在他的theme中将android:windowIsTranslucent改为false
eg:`<item name="android:windowIsTranslucent">false</item>`
2.再加入
`<item name="android:windowDisablePreview">true</item>`
就搞定了

**Comment by CarGuo** [comment]
ok
