### ISSUE TITLE
老编译不过

### ISSUE THREAD

**Issue by kluo88** [CarGuo/GSYGithubAPP#80]
![image](https://user-images.githubusercontent.com/14191745/61448840-4895cf00-a986-11e9-8c08-0bae62a28b3a.png)

![image](https://user-images.githubusercontent.com/14191745/61448885-5e0af900-a986-11e9-8002-81b58641ef80.png)

**Comment by CarGuo** [comment]
react-native run-android 

然后项目是

android.useAndroidX=true
android.enableJetifier=true

的

**Comment by kluo88** [comment]
> react-native run-android
> 
> 然后项目是
> 
> android.useAndroidX=true
> android.enableJetifier=true
> 
> 的

![image](https://user-images.githubusercontent.com/14191745/61449589-d8884880-a987-11e9-889e-49ee21c5552c.png)
你的代码拉出来就配好了

**Comment by kluo88** [comment]
以下下步骤  （npm node 最新）
1.配置
![image](https://user-images.githubusercontent.com/14191745/61523206-79d5d400-aa46-11e9-911d-c66871887a1f.png)

2. npm install 好几条警告
![image](https://user-images.githubusercontent.com/14191745/61522128-472adc00-aa44-11e9-87bf-d76a8436ce8e.png)

3.react-native run-android 有警告。 安装完红错误
![image](https://user-images.githubusercontent.com/14191745/61522291-aa1c7300-aa44-11e9-9775-66b12539800c.png)
![image](https://user-images.githubusercontent.com/14191745/61522575-35960400-aa45-11e9-8c06-f247b062f95a.png)
