### ISSUE TITLE
求助作者大神关于npm install出的问题

### ISSUE THREAD

**Issue by wangwenyu0805** [CarGuo/GSYGithubAPP#90]
我拉取项目之后，执行npm install操作，就一直报错如下：
realm@2.29.2 install: `node-pre-gyp install --fallback-to-build`，
求作者大神帮下忙，谢谢了

**Comment by CarGuo** [comment]
realm 没有安装成功？ 

https://github.com/CarGuo/GSYGithubAPP/issues/50#issuecomment-451480366

**Comment by wangwenyu0805** [comment]
现在realm已经安装成功了，启动的时候，好像作者你的代码提示是这样的：
----------------------------------------------------------------
* 你需要自己在config目录下 创建一个ignoreConfig.js文件
 * 然后输入你的client_id 和 client_secret
 * export const CLIENT_ID = "xxxx";
 * export const CLIENT_SECRET = "xxxx";
-------------------------------------------------------------
想请问下作者，这里的CLIENT_ID 和 CLIENT_SECRET 分别对应什么呢，谢谢了

**Comment by wangwenyu0805** [comment]
github的登录密码吗

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAPP#编译运行流程
