### ISSUE TITLE
uni-app有没有接触过

### ISSUE THREAD

**Issue by Kenguba** [CarGuo/GSYGithubAPP#93]
uni-app有没有接触过,这个好像他们呢的官方说是weex的替代,我看了博主有weex版本的,有没有uni-app版本的呢?

**Comment by CarGuo** [comment]
有用过呢，默认情况下并不是weex，而是webview的视图渲染，需要用到nvue才是weex模式。

本质上我的weex版本和uni-app差别不会很大，不过我这边确实没有完全的weex版本。
